### ISSUE TITLE
Publicly reference-able location for JCuda 0.8.0's license 

### ISSUE THREAD

**Issue by nakul02** [jcuda/jcuda-main#18]
We are using JCuda for Apache SystemML and wanted to be able to distribute the JCuda jars with our releases. 
The jcuda-main (https://github.com/jcuda/jcuda-main) project specifies a MIT License, but there is no LICENSE file for the 0.8.0 tag.

Would it be possible for you to create something publicly reference-able to say that JCuda (& other jcu* artifacts) are released under an MIT License? Maybe on the jcuda.org website?

Tagging @deroneriksson

**Comment by jcuda** [comment]
Yes, the licenses have been added here in the repo after the 0.8.0 tag was created, in response to https://github.com/jcuda/jcuda-main/issues/12 

Independent of that, since 2010-07-11, the license has been (and will be) available under 

http://jcuda.org/License.txt

Is this sufficient for your purposes? 

It is not directly associated with version 0.8.0, and I wonder whether this is so different from the license that is now here in the repo. Is the only problem that version 0.8.0 was released and tagged before the license file was added here? In any case, the *Maven* release happened after the license file was added, and parent POM also refers to http://jcuda.org/License.txt , so I think using the Maven dependency should be safe in this regard - but I'm not a <strike>pettifoggers</strike> lawyer ...

**Comment by nakul02** [comment]
:+1:

I am not a lawyer either, but I think this is sufficient for us!
Thank you!

**Comment by jcuda** [comment]
Assuming that this can be closed now.
