### ISSUE TITLE
CUDA 10?

### ISSUE THREAD

**Issue by blueberry** [jcuda/jcuda-main#27]
Hi @jcuda 

What are your plans regarding support for CUDA 10, and is there anything we can help with?

**Comment by jcuda** [comment]
Of course, the update for CUDA 10 is already on the radar, and I'll try to tackle it during this week. I'll drop notes here when it's ready to build the binaries, that partially depends on how may updates there are.

**Comment by vimalaguti** [comment]
what about other libraries like cuDNN 7.3?

**Comment by jcuda** [comment]
cuDNN was (and still is) a bit of an outsider, because it is only available for NVIDIA registered developers and thus not part of the CUDA SDK. But in the last few versions (I think since CUDA 9), the update for JCuda always included an update for the most recent cuDNN, and I'll try to do this again this time. 

(But I have to mention that my *actual* "work" (i.e. the one that I'm paid for) is eating up a substantial amount of my time, so it's always hard to make promises here...)

**Comment by jcuda** [comment]
Just a short heads-up: I'm working on the update, but the https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__GRAPH.html#group__CUDA__GRAPH is bearing some challenges. I doubt that the functionality can sensibly be mapped to Java in all depth (I mean, they are passing around and storing (callback) function pointers there - we only have *objects* in Java, and managing the state of a callback is already tricky enough). I even considered to omit this part of the API to get the update to 10.0 out earlier. But I'm doing my best, let's see whether this is enough.

**Comment by blueberry** [comment]
Yes, I can imagine how graph API can get unwieldy really fast. Do you perhaps know how many people used nvGraph before? 
Have you looked into javacpp's way of dealing with this? They do have CUDA 10 API for nvGraph, but I don't know whether it supports the part that is giving the challenge at all.

**Comment by jcuda** [comment]
The API that is offered there is not a "usual graph API". (This is already covered with nvGraph and JNvgraph). This API is for defining "execution graphs". So you can define a graph like this 

      A
     / \
    B   C
     \ /
      D

where

- A is a node that copies memory to the device
- B and C are CUDA kernels that each operate on one half of the data
- D is a kernel that combines the results from B and C 

They offered some functionality that raises some issues. For example, you can define a "kernel node", with pseudocode like this
  
    Pointer kernelArgs = { deviceInput, deviceResult };
    CUgraphNode node = createNode(kernelFunction, kernelArgs);

 and *later* obtain a pointer to the kernel arguments that have been given *while* the node was created - bam! That breaks everything for JCuda, because that once was a Java object, and the only thing that can be passed to the internal function for creating the node is a plain pointer. It's not possible to "reconstruct" the Java object from this pointer. Of course, one could return a `CUdeviceptr` at this point, but that seems to be very brittle and may cause unexpected behavior (and in any case, that's not the only issue here...)

JavaCPP might have covered this "implicitly". They have a far more "generic" mapping of Java objects to C data structures. JCuda internally works on structures that made sense for the specific API of CUDA. But a lot has happened in the last 10 years... (It would be time for a cleanup and refactoring, but when the update is done, I'd rather have a look at http://jdk.java.net/panama/ - maybe this comes for the rescue here ;-))

**Comment by blueberry** [comment]
I see. I mentioned JCuda because I’ve seen that they have the release, but I thought that this is about nvGraph. It is possible that they skipped this functionality.

**Comment by blueberry** [comment]
Thanks! I probably won't be able to do the Linux build before you estimated you'd do it yourself, unfortunately.

**Comment by blueberry** [comment]
All ClojureCUDA and Neanderthal tests pass with JCuda 10.0.0.

**Comment by blueberry** [comment]
Thank you very much for releasing the new version with such a smooth transition!

**Comment by jcuda** [comment]
Great, thanks @blueberry , this always gives me some confidence! 

The coverage with *automated* tests in JCuda is rather low: They basically consist of the "Basic JNI binding tests" and very few regression tests. I usually start the samples, which already should give a reasonable coverage, but automated ones would be preferable.

I'll update the website and README ASAP.

**Comment by jcuda** [comment]
This certainly was not "as soon as possible", but finally, the website and README have been updated.
