### ISSUE TITLE
CUDA 11

### ISSUE THREAD

**Issue by blueberry** [jcuda/jcuda-main#35]
Hi Marco,

I've just noticed that Nvidia released CUDA 11 RC, and the final release should follow soon. I've opened this issue so everyone could track the progress (hopefully :) and help you with testing if necessarry.

As usual, I'll try to build JCuda 11 on Linux and help with issues as soon as you find time and motivation to update it to the new CUDA.

Thank you for all this!

**Comment by jcuda** [comment]
Thanks for the heads-up. Of course, I'll try to do the update for CUDA 11 ASAP (and in fact, it would be great if I could already prepare it based on the RC, depending on how much of the API has changed). There are several other pending tasks (one of them being the update of JOCL for OpenCL 3.0...), but I'll try to allocate some time for these and drop a note here when there is something to test.

**Comment by blueberry** [comment]
Hi Marco. 11.0 has been officially released today. (no pressure, just an info :)

**Comment by jcuda** [comment]
\*nervously looks left and right\* Yeah, no pressure, sure ...

;-)

Thanks for the heads-up. I'll try to at least update my installation (and have a look at how many API changes there have been) during the weekend. After that, I should be able to better estimate the effort and timeline for the actual JCuda update.

**Comment by jcuda** [comment]
OK, great. I just noticed that CUDA 11 requires Windows 10. I'll have to do a backup, an update, and am pretty sure that this will cause all sorts of headaches. That's pretty annoying. I'll keep you posted, but don't expect anything too soon here (and in doubt, blame those who think that all this is not just *wrong*).

**Comment by jcuda** [comment]
Another small update: I'll probably buy a new PC instead of trying to upgrade my "ancient" (5 year old) Win 8.1 PC to Windows 10. The risk of breaking things is just too high. A fresh start (with a GPU that has CUDA Compute Capability 7.5, by the way) may be reasonable here. 

(I'll also try to not think about why I'm spending my spare time and money for all that - I've been doing that far too much recently...)

**Comment by blueberry** [comment]
Looking at cuDNN 8, it seems that the API completely changed conceptually. Assuming that cuDNN 7.6 should continue working on CUDA 11, it may be a good idea to upgrade this in two phases: CUDA 11, which should be more or less straightforward, and cuDNN, which requires a lot of work?

**Comment by jcuda** [comment]
Oh dear. Indeed, the list at https://docs.nvidia.com/deeplearning/sdk/cudnn-api/index.html#api-changes looks like "We've only changed one thing (namely all functions). But the rest (i.e. the name of the library) has remained the same".

They also say *"Backward compatibility layer maintains support for cuDNN 7.x"*, which sounds like it should be possible to create a working cuDNN 7.6 + CUDA 11 - combination. But I'll have to carefully investigate this, in order to estimate whether it's worth the effort. To put it that way: I'm not sure whether I want to be "responsible" for possible compatibility issues. We had the same back when they changed their initial CUBLAS to CUBLAS_v2, which was *supposed* to retain some compatibility. In the C world, they tried to re-wire things with lots of (lots of) `#define` statements in the headers. But on the Java side, something like this was not reasonably possible: It was, in fact, a *completely new library*, leading to the state of having `JCublas` and `JCublas2`. 

From skimming *very* quickly over the release notes, they also mention...

>  The cuDNN library has been split into the following libraries:
> `cudnn_ops_infer` ...
> `cudnn_ops_train` ...
> ...

If this is clearly reflected in the headers, then it might make sense to introduce dedicated classes like

`org.jcuda.cudnn8.JCudnnInfer` 
`org.jcuda.cudnn8.JCudnnTrain` 
...

But you're right: The first step will be to update to CUDA 11. Then I'll have a closer look at the new cuDNN API, and see whether it could be sensibly possible to have some sort of "backward compatibility to cuDNN 7.x", or whether this is a "big bang" change that justifies creating a new (and then, hopefully *somewhat* future-proof) incarnation of the bindings.

(And I think that when someone is updating to CUDA 11 and wants to use cuDNN, one can probably expect to update to cuDNN 8 as well. Even *if* they have some sort of "compatibility mode" now, I'm pretty sure it will be dropped quickly in the next CUDA version anyhow...)

**Comment by jcuda** [comment]
I know this took/takes far longer than it should, but... I've been busy with some other tasks, and now finally been moving to my new PC with Win10/CUDA 11 support. I'll try to tackle the update ASAP, so this is comment is mainly to make clear that the update has not been forgotten, and it *will* come, hopefully pretty soon.

**Comment by jcuda** [comment]
The main part of the update for CUDA 11 has been done (it's the current state of the repo, also tagged as `version-11.0.0-RC00`).

@blueberry If you have some time, you might already want to give it a try,  

# but ...

...the update of JCudnn is **not** done yet, and there are still some cleanups necessary for the removal of nvGRAPH. Currently, JCudnn and JNvgraph are just commented out in https://github.com/jcuda/jcuda-main/blob/master/pom.xml#L37 and https://github.com/jcuda/jcuda-main/blob/master/CMakeLists.txt#L45 

I think that many (maybe even most) users of JCuda use it for JCudnn, so the additional delay for the update here is unfortunate, but I'm doing my best. (For free, to emphasize this once more).

**Comment by blueberry** [comment]
Thank you, Marco. I believe I can try it in the following week. I'll post results here.

**Comment by jcuda** [comment]
Sure, thanks. Maybe I can even make some progress with JCudnn until then. In any case, I'd mention possible updates here.

**Comment by blueberry** [comment]
Hi @jcuda

I've tried this today, but the build fails. Summary:

1. I've updated to the latest cuda 11 available in the arch linux repository. That's 11.0.228
2. Followed the build instructions for JCuda.
2.1. cmake-gui seems to work ok. The only odd thing is that cmake couldn't find CUDA_SDK path (TOOKLIK is OK). But then I checked on another computer where I built JCuda 10.2, and this also happens there so it shouldn't be a problem. 
2.2. mvn clean install in jcuda-parrent was successful
2.3. mvn clean install in jcuda-main raised errors.

Here is the relevant part of the output (until then everything was green):

```
[INFO] --------------------------< org.jcuda:jcuda >---------------------------
[INFO] Building jcuda 11.0.0                                             [4/15]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jcuda ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jcuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ jcuda ---
[INFO] Compiling 166 source files to /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/CUmemAllocationProp.java:[52,11] error: cannot find symbol
[ERROR]  class CUmemAllocationProp
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/CUmemAllocationProp.java:[71,120] error: cannot find symbol
[ERROR]  class CUmemAllocationProp
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[13691,8] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[13696,8] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[13713,8] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[13718,8] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[15905,71] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[15909,85] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[15926,72] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/driver/JCudaDriver.java:[15930,85] error: cannot find symbol
[ERROR]  class JCudaDriver
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/runtime/JCuda.java:[6719,8] error: cannot find symbol
[ERROR]  class JCuda
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/runtime/JCuda.java:[6725,8] error: cannot find symbol
[ERROR]  class JCuda
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/runtime/JCuda.java:[6751,12] error: cannot find symbol
[ERROR]  class JCuda
/home/dragan/workspace/java/jcuda/jcuda/JCudaJava/src/main/java/jcuda/runtime/JCuda.java:[6757,8] error: cannot find symbol
[INFO] 14 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jcuda-main 11.0.0:
[INFO] 
[INFO] JCuda .............................................. SUCCESS [  0.592 s]
[INFO] jcuda-common ....................................... SUCCESS [  0.415 s]
[INFO] jcuda-natives ...................................... SUCCESS [  0.120 s]
[INFO] jcuda .............................................. FAILURE [  0.567 s]
[INFO] jcublas-natives .................................... SKIPPED
[INFO] jcublas ............................................ SKIPPED
```

There seems to be a problem with this statement in CUAllocationProp: 
` public CUmemAllocationProp_allocFlags allocFlags; `

Any hints?

**Comment by jcuda** [comment]
Apologies for that: Some new files (i.e. `.java` files that had supposed to be added with the update to CUDA 11) have been missing. I have added them now. This affected several projects, so it's probably best to do a `pull` for each of them.

(I think there was a similar problem in one of the previous updates. The reason for that is that I have some batch files that basically do the commits of the changes automatically for each project. But this only stages *modified* files. Extending this to "all (untracked) files" would be difficult (and may cause some bogus/temp files to be committed accidentally). But I have to find a better solution for this...)

---

An aside: I've mostly done the update for cuDNN as well, but will need some more tests and cleanups. I hope that I can do this tomorrow, or at least not later than during the weekend. 

The reasons why this took particularly long: 

1. I took the opportunity to also clean up my code generator a bit, but it's still far from being publishable...
2. The cuDNN API itself, and their pattern of versioning and deprecation, is a mess.

Seriously: There is my all-time favorite example, [`cudnnRNNBackwardData`](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnRNNBackwardData), receiving 27 (twenty-seven!) parameters. One of the many difficulties for something like this is: By default, my code generator inserts `NULL`-checks for non-primitive parameters. But in this case (or in cuDNN in general), most parameters **may** be `NULL`. Now, I changed the code generator to omit the `NULL` checks. But then, the function bails out with a segfault and crashes the VM. (I mean, it could just return an error code, but it crashes). I could now say: "VM crash? Not my problem". But I'm doing an automated test to see whether the function can at least be called, to avoid `UnsatisfiedLinkError`s - and this is not possible when the VM may randomly be killed during such a test.  It's practically impossible to figure out which parameters may be `NULL` or not.  So in the worst case, I have to consider removing the `NULL`-checks **and** the automated tests - that's not nice...

The good news is: `cudnnRNNBackwardData` is now deprecated!
The bad news is: It has been replaced with [`cudnnRNNBackwardData_v8`](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnRNNBackwardData_v8) ...

**Comment by blueberry** [comment]
Thank you, Marko! 
Now it works as a Swiss clock :) Tried it with ClojureCUDA and Neanderthal.
Here's the linux build. Of course, once you complete cudnn, I'll re-build everything again just in case.
[jcuda-linux.zip](https://github.com/jcuda/jcuda-main/files/5242107/jcuda-linux.zip)

Are the CNN-related APIs changed much, or they are just re-arranged in namespaces? If there's not much substantial changes, I might try to port existing code and test JCudnn as soon as you complete it.

**Comment by jcuda** [comment]
Great. I'll finish the update for cuDNN ASAP, and create a tag in the repos as usual when it's done.

The API changes in cuDNN are ... yeah, well, complex and hard to grasp. One (minor) "enhancement" that I did in the code generator was to also retain the `CUDNN_DEPRECATED` attribute of the functions, and pass it on to Java, so that the Java functions are marked as `@Deprecated` accordingly. Currently, these are 50 functions in JCudnn. In many cases, the deprecations meant that they just added/removed/changed a parameter, and introduced a new function, usually with a `_v8` suffix in the name, that offers a similar functionality, but some parts seem to have changed entirely. 

Before the release, I'd like to update the [jcudnn samples](https://github.com/jcuda/jcuda-samples/tree/master/JCudaSamples/src/main/java/jcuda/jcudnn/samples), as a "proof of concept", to make sure that they are at least basically working. The RNN sample still compiles, but uses dozens of deprecated functions. The MNIST sample contains some (minor) compile errors. I'll try to fix them by comparing them to the official cuDNN samples.

**Comment by jcuda** [comment]
@blueberry I have done the update for cuDNN 8.0.3. The release candidate state is tagged as `version-11.0.0-RC01`, which right now is the same as `master`.

The most important update in terms of the build process (compared to your previous build) is that `JNvgraph` has been removed and `JCudnn` has been added in the CMake files and POM.

I also have updated the samples (including the JCudnn sample), and will push that as soon as JCuda 11.0.0 is released.

**Comment by blueberry** [comment]
I'll see to build these ASAP. I won't be able to test JCudnn since I'll need some time to port everything to 8.0.
Anyway, there's going to be only Linux build, since CUDA 11 is not available on macOS.

**Comment by blueberry** [comment]
Here's the linux binaries. All tests that I have pass. There won't be macOS build since Nvidia no longer support macs and does not release macOS drivers.
[jcuda-natives.zip](https://github.com/jcuda/jcuda-main/files/5252617/jcuda-natives.zip)

**Comment by jcuda** [comment]
So, aplogogies for the delays here, and as usual, thanks to @blueberry for your continued support and patience. JCuda 11 is on its way into Maven Central, and will be available at  
```
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcuda</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcublas</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcufft</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcusparse</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcusolver</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcurand</artifactId>
    <version>11.0.0</version>
</dependency>
<dependency>
    <groupId>org.jcuda</groupId>
    <artifactId>jcudnn</artifactId>
    <version>11.0.0</version>
</dependency>
```
